-- Manager approval workflow for employee certifications and competency changes.
CREATE TABLE IF NOT EXISTS certification_approvals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id),
    name VARCHAR(160) NOT NULL,
    issuer VARCHAR(120),
    issued_date DATE,
    expiry_date DATE,
    submitted_by_user_id INTEGER NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    reviewed_by_user_id INTEGER REFERENCES users(id),
    reviewed_at TIMESTAMP,
    reviewer_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_certification_approvals_status
    ON certification_approvals(status);

CREATE TABLE IF NOT EXISTS competency_assessment_approvals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id INTEGER NOT NULL REFERENCES employees(id),
    skill_id INTEGER NOT NULL REFERENCES skills(id),
    proposed_level INTEGER NOT NULL CHECK (proposed_level BETWEEN 1 AND 5),
    proposed_required_level INTEGER NOT NULL CHECK (proposed_required_level BETWEEN 1 AND 5),
    notes TEXT,
    submitted_by_user_id INTEGER NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL DEFAULT 'Pending',
    reviewed_by_user_id INTEGER REFERENCES users(id),
    reviewed_at TIMESTAMP,
    reviewer_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_competency_assessment_approvals_status
    ON competency_assessment_approvals(status);
CREATE INDEX IF NOT EXISTS ix_competency_assessment_approvals_employee_skill
    ON competency_assessment_approvals(employee_id, skill_id);
